### ISSUE TITLE
Handle exit calls elegantly for broken connection

### ISSUE THREAD

**Issue by t0xic0der** [t0xic0der/sanctuary-zero#10]
![servlost](https://user-images.githubusercontent.com/49605954/90329632-2bd22d80-dfc4-11ea-975e-bf8a451d1904.png)

**Comment by ahmadsyafrudin** [comment]
I think this being Handle By #32 like I mention on comment #27

**Comment by t0xic0der** [comment]
@ahmadsyafrudin The latest commit to `master` breaks it again. Could you please look into it and resolve the same?

**Comment by t0xic0der** [comment]
Oh never mind. I fixed it. It was a small variable referencing error.

**Comment by ahmadsyafrudin** [comment]
Okay. Sure
