### ISSUE TITLE
The time shown at user prompt stays constant

### ISSUE THREAD

**Issue by t0xic0der** [t0xic0der/sanctuary-zero#15]
It usually picks the time when the response was asked and gets refreshed only when the message is sent and a new input call is triggered. The usual behaviour of it should be for the prompt to go on changing with respect to time.

**Comment by gilmouta** [comment]
Hey, I submitted a PR to fix this issue 😃 
I was going to ask to be assigned before submitting, but the solution ended up being simple enough.

**Comment by t0xic0der** [comment]
Yes, I would agree to that. :rofl: 

It happens from time to time, that a lot of minute details are overlooked - when working to solve a bigger problem. Thank you for your attention on this issue and for your pull request.
