### ISSUE TITLE
Add CONTRIBUTING.md and CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by t0xic0der** [t0xic0der/sanctuary-zero#16]
In the spirit of getting more contributors for the project, the above documents would be appreciated.

**Comment by azim2429** [comment]
Hey @t0xic0der can I do this documentation?

**Comment by t0xic0der** [comment]
Sure. The basic documentation are present. Feel free to expand upon them. You can get more information in the project wiki [here](https://github.com/t0xic0der/sanctuary-zero/wiki) and in our community website [here](https://astrosonic.tech/).

Happy Hacktoberfest :smile:

**Comment by t0xic0der** [comment]
Hi @azim2429, Be sure to get yourself registered at https://organize.mlh.io/participants/events/4659-hack-astrosonic, our official Hacktoberfest event to stay in touch with the fellow contributors of this project.

Also, feel free to leave a star on the project - should you find it worth your time. Happy hacking! :smile:

**Comment by azim2429** [comment]
Yes Definitely!

**Comment by pranavpatel3012** [comment]
Hey @t0xic0der , Can I add "Steps to contribute" in the contribute.md file ?

**Comment by t0xic0der** [comment]
@pranavpatel3012, please tag the current assignee and ask if they are okay if the issue is unassigned from their name. Once I get their approval, I will assign this to you and you can go ahead with adding the said contents.

**Comment by pranavpatel3012** [comment]
@t0xic0der thanks for the response.

**Comment by pranavpatel3012** [comment]
Hey @azim2429 , I saw the contribute.md file you added and I think the documentation is perfect. But I think for new comers to Hacktoberfest like me can use the guide/steps to contribute in this repository. So if you don't mind can I add "steps to contribute" section in contribute.mb ?

**Comment by azim2429** [comment]
Yeah Sure!

**Comment by pranavpatel3012** [comment]
Thanks @azim2429 

Hey @t0xic0der, I got the consent to add , Can you please assign this to me now ?

**Comment by t0xic0der** [comment]
Sure. @pranavpatel3012.

Thanks for reaching out promptly. @azim2429.
