### ISSUE TITLE
Package the client application into an executable binary for GNU/Linux

### ISSUE THREAD

**Issue by t0xic0der** [t0xic0der/sanctuary-zero#19]
Make sure that you use PyInstaller and that it is compliant to Python 3.8 and above.

**Comment by Pratik-ahirrao** [comment]
Can i work on this issue?

**Comment by t0xic0der** [comment]
Cool. I will assign you this issue. Be sure to get yourself registered at https://organize.mlh.io/participants/events/4659-hack-astrosonic, our official Hacktoberfest event to stay in touch with the fellow contributors of this project.

Also, feel free to leave a star on the project - should you find it worth your time. Happy hacking! :smile:

**Comment by Pratik-ahirrao** [comment]
Can you help me get started with this issue?

**Comment by t0xic0der** [comment]
Check the following links [here](https://www.pyinstaller.org/) and [here](http://giybf.com/).

**Comment by vinmay** [comment]
@t0xic0der If there hasn't been any activity here, could I take a stab at this ?

**Comment by t0xic0der** [comment]
@vinmay certainly. But first I would ask you to tag the current assignee and comment under the issue asking if they want to pursue the issue or not. If they are willing to have themselves unassigned, I would promptly assign this to you. 

Also, do comment under the issue - should they do not respond under the next 24 hours. Then I would automatically unassign them and give it to you.

**Comment by vinmay** [comment]
@t0xic0der Sure thing.

@Pratik-ahirrao Hey are you still looking into this one?

**Comment by t0xic0der** [comment]
@vinmay I am assigning you this because @Pratik-ahirrao has not responded under 24 hours.

**Comment by vinmay** [comment]
@t0xic0der Had a few questions around this. How do we want to make users add a username and the server address when we open an executable ?

**Comment by t0xic0der** [comment]
The executable binary would be executed on a prompt. So let's assume that we have an executable for GNU/Linux, called `SNCTRYZERO-Client`. Users would need to open themselves a terminal and then navigate to the directory where the executable is located and then perform a `./SNCTRYZERO-Client -u t0xic0der -s ws://localhost:9696/`.

The executable won't be a "double-click-to-open" kind of executable, for what it's worth.

**Comment by t0xic0der** [comment]
Closed #19 via #80
