### ISSUE TITLE
Fetch and display the IPv4/IPv6 address on the verbose

### ISSUE THREAD

**Issue by t0xic0der** [t0xic0der/sanctuary-zero#23]

**Comment by vinmay** [comment]
Where is this expected? I see the IPv4/v6 being displayed here - https://github.com/t0xic0der/sanctuary-zero/blob/master/main.py#L98.

**Comment by t0xic0der** [comment]
The nature of IP address is the only thing displayed. It would be helpful if the IP address is displayed on the server application.

**Comment by vinmay** [comment]
@t0xic0der Ok. I can start with that. Could you assign it to me?

**Comment by t0xic0der** [comment]
Certainly. There you go.

**Comment by shivangswain** [comment]
Assign this to me
