### ISSUE TITLE
Chatroom names are case-sensitive

### ISSUE THREAD

**Issue by t0xic0der** [t0xic0der/sanctuary-zero#24]
Which means `deadbeef` and `DEADBEEF` are same. This is not supposed to happen.

**Comment by Vivek-blip** [comment]
Hey ! ... can i take up this issue
Also i found out that same chatroom names can enter the chatroom and they cant receive messages of each other(those sessions with same chatroom name)

**Comment by t0xic0der** [comment]
> Hey ! ... can i take up this issue

Hi @Vivek-blip, I am assigning this issue to you.

> Also i found out that same chatroom names can enter the chatroom and they cant receive messages of each other(those sessions with same chatroom name)

The password also needs to be the same - else, it ends up creating a new chatroom altogether.

**Comment by Vivek-blip** [comment]
> The password also needs to be the same - else, it ends up creating a new chatroom altogether.
Ya. In the case with same chatroom password, the above issue arise

**Comment by Vivek-blip** [comment]
> Which means `deadbeef` and `DEADBEEF` are same. This is not supposed to happen.

This has to be checked while entering into a already created chatroom using chatroom credentials right

**Comment by t0xic0der** [comment]
One of approaching this is by disallowing entries made in either all caps or in all non-caps but yes, this needs to be checked during chatroom creation/joining.
