### ISSUE TITLE
Add indented wrapping for long messages in client app

### ISSUE THREAD

**Issue by t0xic0der** [t0xic0der/sanctuary-zero#25]
It should not head towards the left side where the time and username are displayed when wrapping. Instead, the wrap should be indented to push it forward by at least 22 characters.

**Comment by nat236919** [comment]
@t0xic0der Let me take a look at this.

**Comment by t0xic0der** [comment]
Yes. Exactly. Do you want this to be assigned to you?

**Comment by nat236919** [comment]
> Yes. Exactly. Do you want this to be assigned to you?

Sure, I'd like to give it a try. Thank you.

**Comment by t0xic0der** [comment]
There you go. I have assigned this issue to you.

Feel free to give stars to the repository if you find it useful.

**Comment by nat236919** [comment]
@t0xic0der Quick question, would it be possible to just limit the text input length?

**Comment by t0xic0der** [comment]
Yes. It is certainly possible. (But that is a workaround @nat236919 and not a solution. Plus we cannot quite control the size of the terminal that the users end up using.)

**Comment by t0xic0der** [comment]
@melsaa would you want to assist @nat236919 on this?

**Comment by melsaa** [comment]
> 
> 
> @melsaa would you want to assist @nat236919 on this?

Sure, I'd be happy to help
