### ISSUE TITLE
Handle SIGABRT in the client application elegantly

### ISSUE THREAD

**Issue by t0xic0der** [t0xic0der/sanctuary-zero#27]
SIGABRT breaks the connection from the server without trace. Make it act just as if it would with SIGINT (Or simply catch SIGABRT and ignore it)

**Comment by ahmadsyafrudin** [comment]
Hi @t0xic0der , I think I can help. 
Server and Client Running:
<img width="1333" alt="Screen Shot 2020-10-15 at 02 07 34" src="https://user-images.githubusercontent.com/11618498/96034920-78cf6480-0e8c-11eb-992b-aad6625362af.png">
Find Process and Kill PID with SIGABRT :
<img width="850" alt="Screen Shot 2020-10-15 at 02 09 06" src="https://user-images.githubusercontent.com/11618498/96034955-81279f80-0e8c-11eb-84cb-8d280b6dd036.png">
Server App Down Message:
<img width="611" alt="Screen Shot 2020-10-15 at 02 13 51" src="https://user-images.githubusercontent.com/11618498/96035042-a3212200-0e8c-11eb-93db-69f156ca9ea2.png">
When I try to send message and hit enter, Client Close with these message:
<img width="719" alt="Screen Shot 2020-10-15 at 02 14 10" src="https://user-images.githubusercontent.com/11618498/96035046-a6b4a900-0e8c-11eb-87aa-d3be03d8138f.png">

If you think this is Ok, I'll Create the PR. Thanks

**Comment by t0xic0der** [comment]
Awesome! Let me quickly assign you this issue and get into reviewing your pull request. :smile:
