### ISSUE TITLE
Users with the same username should not be able to join the chatroom

### ISSUE THREAD

**Issue by t0xic0der** [t0xic0der/sanctuary-zero#35]
Check the presence of the username in the chatroom. If they exist, disallow joining. Let them join otherwise.

**Comment by t0xic0der** [comment]
![image](https://user-images.githubusercontent.com/49605954/96128751-63514d80-0f13-11eb-9d36-a5e2e7d14fb2.png)

**Comment by Vivek-blip** [comment]
Can i work on this one

**Comment by t0xic0der** [comment]
Sure. I have assigned this to you.

**Comment by Vivek-blip** [comment]
One solution for this issue would be to check for username presence inside the server through websocket
since the USERS  data is stored inside server this is a viable solution
What do u think? Any other solution?

**Comment by t0xic0der** [comment]
This is a good solution. It can be slow at times but it ensures the consistency.
