### ISSUE TITLE
'clear' is not recognized

### ISSUE THREAD

**Issue by nat236919** [t0xic0der/sanctuary-zero#51]
## Description
As written, a terminal is cleared using **os.system("clear")**; however, a Windows' clear command does not use **clear**, instead, it uses **cls**. Therefore, I would suggest we check the OS before using clearing command.

## Screenshot
![image](https://user-images.githubusercontent.com/9074112/96327036-84778280-1068-11eb-871e-de8189e6fc94.png)

**Comment by t0xic0der** [comment]
We make use of [`click`](https://click.palletsprojects.com/) here so an elegant answer to this would be using [`click.clear()`](https://click.palletsprojects.com/en/7.x/api/?highlight=clear#click.clear). What do you think?

For your reference @Vivek-blip @vinmay @gilmouta @melsaa @shivangswain

**Comment by vinmay** [comment]
@t0xic0der Unfortunately, Python doesn't have anything internally for this. Checking the OS to clearing the screen just doesn't feel clean. Using `click` sounds like a good way to go about it.  We already use the package so it isn't an overhead either that we are adding.

**Comment by t0xic0der** [comment]
> Checking the OS to clearing the screen just doesn't feel clean.

That is true. 

> We already use the package so it isn't an overhead either that we are adding.

One of the reasons why I sticking to `click` for this operation, is because nothing needs to be added more and we are already using `click` for tons of other operations.
