### ISSUE TITLE
An empty username is allowed during chatroom creation/joining

### ISSUE THREAD

**Issue by t0xic0der** [t0xic0der/sanctuary-zero#53]
This looks bad. We need to disallow blank names using space check.

![image](https://user-images.githubusercontent.com/49605954/96328343-9d2f6a80-105f-11eb-9230-a9f0e1c29703.png)

**Comment by Vivek-blip** [comment]
Can i take up and solve this issue ?

**Comment by t0xic0der** [comment]
Please get over #35 first before moving on to your next assignment.

**Comment by gitarthasarma** [comment]
Is this issue resolved? There is a `emty find` validator class in `/cnew.py` which should solve the problem.

**Comment by Vivek-blip** [comment]
> Is this issue resolved? There is a emtyfind validator class in /cnew.py which should solve the problem.

Ya that's right. This issue shouldn't be there

**Comment by t0xic0der** [comment]
Let me check again if the issue persists.

**Comment by t0xic0der** [comment]
There is another issue which is caused by empty username. A comparison cannot be drawn for an empty username (as the entire space gets trimmed - leaving a string with zero length to be compared with the one at the client-side). So a message is printed twice in the client-side. 

![image](https://user-images.githubusercontent.com/49605954/96338589-e528ae80-10ac-11eb-8fed-d064c91649c6.png)

Such an issue does not occur with usernames which are not null.

**Comment by t0xic0der** [comment]
> Is this issue resolved? There is a emtyfind validator class in /cnew.py which should solve the problem.

The `emtyfind` class does not allow for sending empty messages. But what if the username itself is empty?

**Comment by gitarthasarma** [comment]
For that case we can use the `len()` function to check whether the string is empty or not. If not then raise an error.

**Comment by t0xic0der** [comment]
> For that case we can use the len() function to check whether the string is empty or not. If empty then raise an error.

I don't think that would work. People can still fill in a string consisting of spaces.

**Comment by gitarthasarma** [comment]
> > For that case we can use the len() function to check whether the string is empty or not. If empty then raise an error.
> 
> I don't think that would work. People can still fill in a string consisting of spaces.

Ohh, correct, maybe we need to then strip all spaces and check if the string is still empty, and then proceed.

**Comment by t0xic0der** [comment]
#59 

For your reference, @gitarthasarma
