### ISSUE TITLE
Codebase is not entirely updated with merged PR (43)

### ISSUE THREAD

**Issue by nat236919** [t0xic0der/sanctuary-zero#60]
PR (https://github.com/t0xic0der/sanctuary-zero/pull/43)

It has come to my attention that the code is missing some updated parts; for example:

1. https://github.com/t0xic0der/sanctuary-zero/blob/master/cnew.py#L54 - It is missing **prompt_continuation**
2. https://github.com/t0xic0der/sanctuary-zero/blob/master/main.py#L35-L48 - duplicate function

@t0xic0der Would you like me to create a PR to patch this?

**Comment by t0xic0der** [comment]
Thank you for marking this out, @nat236919. Those were lost during conflict resolution I think. Please go ahead and create a patch to resolve this.

**Comment by t0xic0der** [comment]
Resolved #60 via #61
