### ISSUE TITLE
Package the server application for Windows 10

### ISSUE THREAD

**Issue by t0xic0der** [t0xic0der/sanctuary-zero#67]
Use PyInstaller to generate an EXE file for the server application. That file should have all the constituting dependencies packaged inside it.

**Comment by s0umadeep** [comment]
Hi @t0xic0der ,

Kindly assign this issue to me.

Thanks and Regards,
Soumadeep

**Comment by t0xic0der** [comment]
Cool. I am assigning this issue to you.

Leave a star at this repository, if you find it helpful.
