### ISSUE TITLE
Elegantly detect unresolvable websockets URI

### ISSUE THREAD

**Issue by s0umadeep** [t0xic0der/sanctuary-zero#68]
An invalid websockets URI must be detected correctly and an elegant exit must be made.

**Comment by t0xic0der** [comment]
That is true. When an invalid URI is encountered, it throws out an unprecedented error. This must be worked upon.

**Comment by gitarthasarma** [comment]
Can you assign this to me?

**Comment by t0xic0der** [comment]
Sure @gitarthasarma. I am assigning this issue to you.

Do leave a star at this repository if you find it helpful.

**Comment by t0xic0der** [comment]
Closed #68 via #77. 

Thank you @gitarthasarma for your wonderful contribution. :smile:
